name: Java CI

on: [push]

jobs:
  build-on-bash:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      shell: bash
      run: mvn package
    - name: Deploy package
      shell: bash
      run: mvn deploy -Dtoken=${{ secrets.GITHUB_TOKEN }}

  build-with-default-shell:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      shell: bash
      run: mvn package
    - name: Deploy package
      run: mvn deploy -Dtoken=${{ secrets.GITHUB_TOKEN }}
      
